//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_API.sms.didimo.es {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingRequest", Namespace="https://sms.didimo.es/wcf/PingRequest")]
    [System.SerializableAttribute()]
    public partial class PingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="https://sms.didimo.es/wcf/BaseResult")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.GetMessageStatusResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.CreateMessageResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.CreateSendResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.MessageSendResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.GetCreditsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.GetMessageIdResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAP_API.sms.didimo.es.PingResult))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessageStatusResult", Namespace="https://sms.didimo.es/wcf/GetMessageStatusResult")]
    [System.SerializableAttribute()]
    public partial class GetMessageStatusResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateMessageResult", Namespace="https://sms.didimo.es/wcf/CreateMessageResult")]
    [System.SerializableAttribute()]
    public partial class CreateMessageResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateSendResult", Namespace="https://sms.didimo.es/wcf/CreateSendResult")]
    [System.SerializableAttribute()]
    public partial class CreateSendResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_API.sms.didimo.es.MessageSendResult[] OutputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_API.sms.didimo.es.MessageSendResult[] Output {
            get {
                return this.OutputField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputField, value) != true)) {
                    this.OutputField = value;
                    this.RaisePropertyChanged("Output");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageSendResult", Namespace="https://sms.didimo.es/wcf/CreateSendResult/MessageSendResult")]
    [System.SerializableAttribute()]
    public partial class MessageSendResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCreditsResult", Namespace="https://sms.didimo.es/wcf/GetCreditsResult")]
    [System.SerializableAttribute()]
    public partial class GetCreditsResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credits {
            get {
                return this.CreditsField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditsField, value) != true)) {
                    this.CreditsField = value;
                    this.RaisePropertyChanged("Credits");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessageIdResult", Namespace="https://sms.didimo.es/wcf/GetMessageIdResult")]
    [System.SerializableAttribute()]
    public partial class GetMessageIdResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Output {
            get {
                return this.OutputField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputField, value) != true)) {
                    this.OutputField = value;
                    this.RaisePropertyChanged("Output");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResult", Namespace="https://sms.didimo.es/wcf/PingResult")]
    [System.SerializableAttribute()]
    public partial class PingResult : SOAP_API.sms.didimo.es.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Output {
            get {
                return this.OutputField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputField, value) != true)) {
                    this.OutputField = value;
                    this.RaisePropertyChanged("Output");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessageIdRequest", Namespace="https://sms.didimo.es/wcf/GetMessageIdRequest")]
    [System.SerializableAttribute()]
    public partial class GetMessageIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateSendRequest", Namespace="https://sms.didimo.es/wcf/CreateSendRequest")]
    [System.SerializableAttribute()]
    public partial class CreateSendRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        private SOAP_API.sms.didimo.es.MessageSend[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ScheduleDate {
            get {
                return this.ScheduleDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleDateField, value) != true)) {
                    this.ScheduleDateField = value;
                    this.RaisePropertyChanged("ScheduleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public SOAP_API.sms.didimo.es.MessageSend[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageSend", Namespace="https://sms.didimo.es/wcf/CreateSendRequest/MessageSend")]
    [System.SerializableAttribute()]
    public partial class MessageSend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsUnicodeField;
        
        private string MobileField;
        
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsUnicodeField, value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateMessageRequest", Namespace="https://sms.didimo.es/wcf/CreateMessageRequest")]
    [System.SerializableAttribute()]
    public partial class CreateMessageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        private string TextField;
        
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsUnicodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ScheduleDate {
            get {
                return this.ScheduleDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleDateField, value) != true)) {
                    this.ScheduleDateField = value;
                    this.RaisePropertyChanged("ScheduleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsUnicodeField, value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessageStatusRequest", Namespace="https://sms.didimo.es/wcf/GetMessageStatusRequest")]
    [System.SerializableAttribute()]
    public partial class GetMessageStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCreditsRequest", Namespace="https://sms.didimo.es/wcf/GetCreditsRequest")]
    [System.SerializableAttribute()]
    public partial class GetCreditsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertifyFileRequest", Namespace="https://sms.didimo.es/wcf/GetCertifyFileRequest")]
    [System.SerializableAttribute()]
    public partial class GetCertifyFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sms.didimo.es/wcf", ConfigurationName="sms.didimo.es.wcfService")]
    public interface wcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/Ping", ReplyAction="https://sms.didimo.es/wcf/wcfService/PingResponse")]
        SOAP_API.sms.didimo.es.PingResult Ping(SOAP_API.sms.didimo.es.PingRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/Ping", ReplyAction="https://sms.didimo.es/wcf/wcfService/PingResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.PingResult> PingAsync(SOAP_API.sms.didimo.es.PingRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetMessageId", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetMessageIdResponse")]
        SOAP_API.sms.didimo.es.GetMessageIdResult GetMessageId(SOAP_API.sms.didimo.es.GetMessageIdRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetMessageId", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetMessageIdResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.GetMessageIdResult> GetMessageIdAsync(SOAP_API.sms.didimo.es.GetMessageIdRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateSend", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateSendResponse")]
        SOAP_API.sms.didimo.es.CreateSendResult CreateSend(SOAP_API.sms.didimo.es.CreateSendRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateSend", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateSendResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateSendResult> CreateSendAsync(SOAP_API.sms.didimo.es.CreateSendRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateMessage", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateMessageResponse")]
        SOAP_API.sms.didimo.es.CreateMessageResult CreateMessage(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateMessage", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateMessageResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateMessageResult> CreateMessageAsync(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetMessageStatus", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetMessageStatusResponse")]
        SOAP_API.sms.didimo.es.GetMessageStatusResult GetMessageStatus(SOAP_API.sms.didimo.es.GetMessageStatusRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetMessageStatus", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetMessageStatusResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.GetMessageStatusResult> GetMessageStatusAsync(SOAP_API.sms.didimo.es.GetMessageStatusRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetCredits", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetCreditsResponse")]
        SOAP_API.sms.didimo.es.GetCreditsResult GetCredits(SOAP_API.sms.didimo.es.GetCreditsRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetCredits", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetCreditsResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.GetCreditsResult> GetCreditsAsync(SOAP_API.sms.didimo.es.GetCreditsRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateCertifiedSend", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateCertifiedSendResponse")]
        SOAP_API.sms.didimo.es.CreateSendResult CreateCertifiedSend(SOAP_API.sms.didimo.es.CreateSendRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateCertifiedSend", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateCertifiedSendResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateSendResult> CreateCertifiedSendAsync(SOAP_API.sms.didimo.es.CreateSendRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateCertifiedMessage", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateCertifiedMessageResponse")]
        SOAP_API.sms.didimo.es.CreateMessageResult CreateCertifiedMessage(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/CreateCertifiedMessage", ReplyAction="https://sms.didimo.es/wcf/wcfService/CreateCertifiedMessageResponse")]
        System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateMessageResult> CreateCertifiedMessageAsync(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetCertifyFile", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetCertifyFileResponse")]
        System.IO.Stream GetCertifyFile(SOAP_API.sms.didimo.es.GetCertifyFileRequest inputdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://sms.didimo.es/wcf/wcfService/GetCertifyFile", ReplyAction="https://sms.didimo.es/wcf/wcfService/GetCertifyFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetCertifyFileAsync(SOAP_API.sms.didimo.es.GetCertifyFileRequest inputdata);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wcfServiceChannel : SOAP_API.sms.didimo.es.wcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wcfServiceClient : System.ServiceModel.ClientBase<SOAP_API.sms.didimo.es.wcfService>, SOAP_API.sms.didimo.es.wcfService {
        
        public wcfServiceClient() {
        }
        
        public wcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAP_API.sms.didimo.es.PingResult Ping(SOAP_API.sms.didimo.es.PingRequest inputdata) {
            return base.Channel.Ping(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.PingResult> PingAsync(SOAP_API.sms.didimo.es.PingRequest inputdata) {
            return base.Channel.PingAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.GetMessageIdResult GetMessageId(SOAP_API.sms.didimo.es.GetMessageIdRequest inputdata) {
            return base.Channel.GetMessageId(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.GetMessageIdResult> GetMessageIdAsync(SOAP_API.sms.didimo.es.GetMessageIdRequest inputdata) {
            return base.Channel.GetMessageIdAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.CreateSendResult CreateSend(SOAP_API.sms.didimo.es.CreateSendRequest inputdata) {
            return base.Channel.CreateSend(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateSendResult> CreateSendAsync(SOAP_API.sms.didimo.es.CreateSendRequest inputdata) {
            return base.Channel.CreateSendAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.CreateMessageResult CreateMessage(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata) {
            return base.Channel.CreateMessage(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateMessageResult> CreateMessageAsync(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata) {
            return base.Channel.CreateMessageAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.GetMessageStatusResult GetMessageStatus(SOAP_API.sms.didimo.es.GetMessageStatusRequest inputdata) {
            return base.Channel.GetMessageStatus(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.GetMessageStatusResult> GetMessageStatusAsync(SOAP_API.sms.didimo.es.GetMessageStatusRequest inputdata) {
            return base.Channel.GetMessageStatusAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.GetCreditsResult GetCredits(SOAP_API.sms.didimo.es.GetCreditsRequest inputdata) {
            return base.Channel.GetCredits(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.GetCreditsResult> GetCreditsAsync(SOAP_API.sms.didimo.es.GetCreditsRequest inputdata) {
            return base.Channel.GetCreditsAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.CreateSendResult CreateCertifiedSend(SOAP_API.sms.didimo.es.CreateSendRequest inputdata) {
            return base.Channel.CreateCertifiedSend(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateSendResult> CreateCertifiedSendAsync(SOAP_API.sms.didimo.es.CreateSendRequest inputdata) {
            return base.Channel.CreateCertifiedSendAsync(inputdata);
        }
        
        public SOAP_API.sms.didimo.es.CreateMessageResult CreateCertifiedMessage(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata) {
            return base.Channel.CreateCertifiedMessage(inputdata);
        }
        
        public System.Threading.Tasks.Task<SOAP_API.sms.didimo.es.CreateMessageResult> CreateCertifiedMessageAsync(SOAP_API.sms.didimo.es.CreateMessageRequest inputdata) {
            return base.Channel.CreateCertifiedMessageAsync(inputdata);
        }
        
        public System.IO.Stream GetCertifyFile(SOAP_API.sms.didimo.es.GetCertifyFileRequest inputdata) {
            return base.Channel.GetCertifyFile(inputdata);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetCertifyFileAsync(SOAP_API.sms.didimo.es.GetCertifyFileRequest inputdata) {
            return base.Channel.GetCertifyFileAsync(inputdata);
        }
    }
}
